version: "3"
services:
  api-server:
    image: timmy
    env_file:
      - .env
    ports:
      - "5000:5000"
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27018:27017"
      